### ISSUE TITLE
Where are the samples?

### ISSUE THREAD

**Issue by ashalkhakov** [Zebra/LinkOS-WindowsMobileCE-Samples#1]
All I see is EULA.

**Comment by ssizebra** [comment]
We need to click on the "branches" in order to see the content
![image](https://user-images.githubusercontent.com/10078694/34948487-e04db584-f9d2-11e7-916d-e279758870ee.png)

**Comment by ashalkhakov** [comment]
Thank you! I actually found it out but it still seems a bit unconventional.
